export default () => ({
  allProducts: [
    {
      title: "Best sellers",
      items: [
        {
          pid: "pid1",
          name: "Men College School Bag Laptop Backpack For Men 17.3''Large-capacity Backpack USB Port Bag Business Backpack Oxford Waterproof",
          price_diff: 200,
          price: 220,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Thermaltake S100 Tempered Glass Snow Edition Micro-ATX mini-Tower Computer Case with 120mm Rear Fan Pre-Installed CA-1Q9-00S6WN-00, White",
          price_diff: 200,
          price: 600,
          image:
          "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 10,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "Reditor67",
        },
        {
          pid: "pid1",
          name: "Broadlink RM4 pro Smart IR/RF Remote Control Hub with Sensor Cable-WiFi IR/RF Blaster for Smart Home Automation, TV, Curtain, Shades Remote, Works with Alexa...",
          price_diff: 330,
          price: 330,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 50,
          collateral: 15,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "Hosky67",
        },
        {
          pid: "pid1",
          name: "Men's New 100% Cotton American Hoodies Autumn Winter Vintage Long Sleeve Pullover Hard Rock Band Pink Sweater Floyds Hoodie",
          price_diff: 200,
          price: 150,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "2 Slots",
          stock_supply: 5,
          collateral: 30,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "JenniferPro",
        },
        {
          pid: "pid1",
          name: "Don't Believe Everything You Think by Joseph Nguyen Why Your Thinking Is The Beginning & End Of Suffering Paperback English Book",
          price_diff: 200,
          price: 150,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "2 Slots",
          stock_supply: 5,
          collateral: 30,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "JenniferPro",
        },

        {
          pid: "pid1",
          name: "Men Outdoor Hiking Jackets Waterproof Hooded Windbreaker Coat Men Casual Camping Jacket Tactics Military Jackets Men",
          price_diff: 200,
          price: 125,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "3 Slots",
          stock_supply: 5,
          collateral: 17,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "CharlesVitalik",
        },

        {
          pid: "pid1",
          name: "Men's Sneakers Casual Sports Shoes for Men Lightweight PU Leather Breathable Shoe Mens Flat White Tenis Shoes",
          price_diff: 200,
          price: 200,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 30,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Silicone Protective Case Cover for AirPods Pro 3 Storage Box Bluetooth Earphone Sleeve Accessories",
          price_diff: 200,
          price: 140,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 15,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Cotton Oxford Shirt For Mens Long Sleeve Plaid Striped Casual Shirts Male Pocket Regular-Fit Button-Down Work Man Shirt",
          price_diff: 200,
          price: 170,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Face Towel Absorbent Pure Hand Face Cleaning Hair Shower Microfiber Towels Bathroom Home Hotel for Adults",
          price_diff: 200,
          price: 100,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },
      ],
    },
    {
      title: "Explore",
      items: [
        {
          pid: "pid1",
          name: "Men College School Bag Laptop Backpack For Men 17.3''Large-capacity Backpack USB Port Bag Business Backpack Oxford Waterproof",
          price_diff: 200,
          price: 220,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Thermaltake S100 Tempered Glass Snow Edition Micro-ATX mini-Tower Computer Case with 120mm Rear Fan Pre-Installed CA-1Q9-00S6WN-00, White",
          price_diff: 200,
          price: 600,
          image:
          "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 10,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "Reditor67",
        },
        {
          pid: "pid1",
          name: "Cotton Oxford Man Leisure Embroidered Horse Shirts Streetwear Oversized Men Shirt Floral Long Sleeve Casual Plus Size",
          price_diff: 330,
          price: 330,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 50,
          collateral: 15,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "Hosky67",
        },

        {
          pid: "pid1",
          name: "Aluminum Bathroom Shelves Corner Shower Shelf Wall Mount Shampoo Storage Rack Holders No Drill Kitchen Bathroom Accessories",
          price_diff: 200,
          price: 150,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "2 Slots",
          stock_supply: 5,
          collateral: 30,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "JenniferPro",
        },

        {
          pid: "pid1",
          name: "Durable Silicone Soft Accessories Handle Case Protective Case Protect Shell Gamepad Game Controller Cover For PS5",
          price_diff: 200,
          price: 125,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "3 Slots",
          stock_supply: 5,
          collateral: 17,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "CharlesVitalik",
        },

        {
          pid: "pid1",
          name: "Men's Sneakers Casual Sports Shoes for Men Lightweight PU Leather Breathable Shoe Mens Flat White Tenis Shoes",
          price_diff: 200,
          price: 200,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 30,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Elastic Shoes for Men Trend Casual Brand Leather Shoes 2023 New Sneakers Men Comfortable Walking Flats Slip on Man Loafers",
          price_diff: 200,
          price: 140,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 15,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Astronaut Figure Statue Figurine Spaceman Sculpture Educational Toy Desktop Home Decoration Astronaut Model For Kids Gift",
          price_diff: 200,
          price: 170,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },

        {
          pid: "pid1",
          name: "RZX DDR4 RAM Memoria 32GB 8GB 16GB 2400MHz 2666MHz 3200MHz DIMM Desktop Computer Memory Rams",
          price_diff: 200,
          price: 100,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },

        {
          pid: "pid1",
          name: "Waterproof Laptop Backpack Men USB 18 Inch Backpacks Oxford Black Solid Color Large Capacity Rucksacks Teen Student School Bags",
          price_diff: 200,
          price: 210,
          image:
            "https://pairfy.dev/api/media/get-image/z9hZxd7n3PM7Ig1qVld8",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "TheRock77",
        },
      ],
    },
    {
      title: "NFT",
      items: [
        {
          pid: "pid1",
          name: "NFT Mockup",
          price_diff: 200,
          price: 2200,
          image:
            "https://i.seadn.io/gae/61_SX93lc0ANnnUONYpN0lKvgTW3CDbX3CAaET5yV4qrzcpERAZIFa_wJAFZvo4JU3kN4iAZNju01gDsinwY7DKGrlW_qBhufxPU?auto=format&dpr=1&w=128",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 40,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "Tony66",
        },

        {
          pid: "pid1",
          name: "NFT Mockup",
          price_diff: 200,
          price: 1200,
          image:
            "https://i.seadn.io/s/raw/files/9b832f79c79d9bec089d546fc24b30d4.png",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 240,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "Tony66",
        },

        {
          pid: "pid1",
          name: "NFT Mockup",
          price_diff: 200,
          price: 1200,
          image:
            "https://i.seadn.io/s/raw/files/a773be6b3bef3ac484084f364bf528c8.png?auto=format&dpr=1&w=128",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 100,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-a)",
          discount_label: "Tony66",
        },
      ],
    },
  ],
});
