export default () => ({
  allProducts: [
    {
      title: "Cardano best sellers",
      items: [
        {
          pid: "pid1",
          name: "Tailored comfort in azure cotton, unveiling timeless style and contemporary sophistication for a graceful",
          price_diff: 200,
          price: 220,
          image:
            "https://ae01.alicdn.com/kf/S353ebdf1639c4bbebe3636bf7c79da41t.jpg_480x480.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Tailored comfort in azure cotton, unveiling timeless style and contemporary sophistication for a graceful",
          price_diff: 200,
          price: 300,
          image:
            "https://ae01.alicdn.com/kf/Sa820fb5952264ddb85ee55e3d55f5c20u/JONSBO-U4Mini-Case-Black-White-MESH-360-Cold-Row-Position-Support-Back-Plug-Motherboard-MicroATX-Desktop.jpg_350x350xz.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "Reditor67",
        },
        {
          pid: "pid1",
          name: "Tailored comfort in azure cotton, unveiling timeless style and contemporary sophistication for a graceful",
          price_diff: 330,
          price: 330,
          image:
            " https://ae01.alicdn.com/kf/Sec8976097adf4c3ba9d34b9e61f18204n.jpg_480x480.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 50,
          collateral: 15,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "Hosky67",
        },

        {
          pid: "pid1",
          name: "Tailored comfort in azure cotton, unveiling timeless style and contemporary sophistication for a graceful",
          price_diff: 200,
          price: 420,
          image:
            "https://ae01.alicdn.com/kf/Sd8a92c5e8a6b4ef5860314ebb60ef8cd6/All-aluminum-alloy-matx-small-computer-case-atx-desktop-nas-main-box-mini-shell-multi-drawer.jpg_350x350xz.jpg_.webp",
          payment_type: "2 Slots",
          stock_supply: 5,
          collateral: 30,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "JenniferPro",
        },

        {
          pid: "pid1",
          name: "Tailored comfort in azure cotton, unveiling timeless style and contemporary sophistication for a graceful",
          price_diff: 200,
          price: 220,
          image:
            "https://ae04.alicdn.com/kf/S71250d5f8670447bbab8db77fd2da2e05/2023-New-Columbia-Men-s-Sprint-Jacket-Lightweight-Coat-Camping-Mountaineering-Fashion-Hooded-Jacket-Windproof-Coat.jpg_220x220xz.jpg_.webp",
          payment_type: "3 Slots",
          stock_supply: 5,
          collateral: 17,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "CharlesVitalik",
        },

        {
          pid: "pid1",
          name: "Tailored comfort in azure cotton, unveiling timeless style and contemporary sophistication for a graceful",
          price_diff: 200,
          price: 100,
          image:
            "https://ae01.alicdn.com/kf/S15575f1efc64479d99bff7815a8903c1k.jpg_480x480.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },

        {
          pid: "pid1",
          name: "Waterproof hooded jacket four colors",
          price_diff: 200,
          price: 100,
          image:
            "https://ae01.alicdn.com/kf/Hf2fce96804694f44b63031f7e9123a7dY.jpg_480x480.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },

        {
          pid: "pid1",
          name: "Tailored comfort in azure cotton, unveiling timeless style and contemporary sophistication for a graceful timeless style and contemporary sophistication for a graceful",
          price_diff: 200,
          price: 100,
          image:
            "https://ae04.alicdn.com/kf/S1728e9ed54894f90bcc37a8c22117b4eL/Men-s-T-Shirt-Pure-Color-V-Collar-Short-Sleeved-Tops-Tees-Men-T-Shirt-Black.jpg_220x220xz.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },

        {
          pid: "pid1",
          name: "Tailored comfort in azure cotton, unveiling timeless style and contemporary sophistication for a graceful",
          price_diff: 200,
          price: 100,
          image:
            "https://ae01.alicdn.com/kf/Sd1e9dd73bc374a00ac9fc7862da56f54R.jpg_480x480.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },

        {
          pid: "pid1",
          name: "Tailored comfort in azure cotton, unveiling timeless style and contemporary sophistication for a graceful",
          price_diff: 200,
          price: 100,
          image:
            "https://ae04.alicdn.com/kf/S3763ec7f3b45441185bb520397afed00W/Brand-BPA-Free-Leak-Proof-Sports-Water-Bottle-High-Quality-Tour-Hiking-Portable-My-Favorite-Drink.jpg_220x220xz.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },
      ],
    },
  ],
});
