export default () => ({
  allProducts: [
    {
      title: "Cardano best sellers",
      items: [
        {
          pid: "pid1",
          name: "2 Pack Wired Headphones with 3.5mm Jack with Microphone, Volume Control, Noise Isolating Wired Headphones for 3.5mm Jack Headphones",
          price_diff: 200,
          price: 220,
          image:
            "https://ae01.alicdn.com/kf/S353ebdf1639c4bbebe3636bf7c79da41t.jpg_480x480.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Thermaltake S100 Tempered Glass Snow Edition Micro-ATX mini-Tower Computer Case with 120mm Rear Fan Pre-Installed CA-1Q9-00S6WN-00, White",
          price_diff: 200,
          price: 600,
          image:
            "https://ae01.alicdn.com/kf/Sa820fb5952264ddb85ee55e3d55f5c20u/JONSBO-U4Mini-Case-Black-White-MESH-360-Cold-Row-Position-Support-Back-Plug-Motherboard-MicroATX-Desktop.jpg_350x350xz.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 10,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "Reditor67",
        },
        {
          pid: "pid1",
          name: "Broadlink RM4 pro Smart IR/RF Remote Control Hub with Sensor Cable-WiFi IR/RF Blaster for Smart Home Automation, TV, Curtain, Shades Remote, Works with Alexa...",
          price_diff: 330,
          price: 330,
          image:
            " https://ae01.alicdn.com/kf/Sec8976097adf4c3ba9d34b9e61f18204n.jpg_480x480.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 50,
          collateral: 15,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "Hosky67",
        },

        {
          pid: "pid1",
          name: "Don't Believe Everything You Think by Joseph Nguyen Why Your Thinking Is The Beginning & End Of Suffering Paperback English Book",
          price_diff: 200,
          price: 150,
          image:
            "https://ae01.alicdn.com/kf/Sf00dab3ecec344f78eb335a4fe1003c2c/Don-t-Believe-Everything-You-Think-by-Joseph-Nguyen-Why-Your-Thinking-Is-The-Beginning-End.jpg_350x350xz.jpg_.webp",
          payment_type: "2 Slots",
          stock_supply: 5,
          collateral: 30,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "JenniferPro",
        },

        {
          pid: "pid1",
          name: "Men Outdoor Hiking Jackets Waterproof Hooded Windbreaker Coat Men Casual Camping Jacket Tactics Military Jackets Men",
          price_diff: 200,
          price: 125,
          image:
            "https://ae01.alicdn.com/kf/S40c424d157d04003bd9b90539e0f6a8ao/Men-Outdoor-Hiking-Jackets-Waterproof-Hooded-Windbreaker-Coat-Men-Casual-Camping-Jacket-Tactics-Military-Jackets-Men.jpg_350x350xz.jpg_.webp",
          payment_type: "3 Slots",
          stock_supply: 5,
          collateral: 17,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "CharlesVitalik",
        },

        {
          pid: "pid1",
          name: "Men's Sneakers Casual Sports Shoes for Men Lightweight PU Leather Breathable Shoe Mens Flat White Tenis Shoes",
          price_diff: 200,
          price: 200,
          image:
            "https://ae01.alicdn.com/kf/Hf2fce96804694f44b63031f7e9123a7dY.jpg_480x480.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 30,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Silicone Protective Case Cover for AirPods Pro 3 Storage Box Bluetooth Earphone Sleeve Accessories",
          price_diff: 200,
          price: 140,
          image:
            "https://ae01.alicdn.com/kf/S15a3c27f0238440fb06bfc9b82dfc0baq/Silicone-Protective-Case-Cover-for-AirPods-Pro-3-Storage-Box-Bluetooth-Earphone-Sleeve-Accessories.jpg_350x350xz.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 15,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },
        {
          pid: "pid1",
          name: "Cotton Oxford Shirt For Mens Long Sleeve Plaid Striped Casual Shirts Male Pocket Regular-Fit Button-Down Work Man Shirt",
          price_diff: 200,
          price: 170,
          image:
            "https://ae04.alicdn.com/kf/S1728e9ed54894f90bcc37a8c22117b4eL/Men-s-T-Shirt-Pure-Color-V-Collar-Short-Sleeved-Tops-Tees-Men-T-Shirt-Black.jpg_220x220xz.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },

        {
          pid: "pid1",
          name: "Face Towel Absorbent Pure Hand Face Cleaning Hair Shower Microfiber Towels Bathroom Home Hotel for Adults",
          price_diff: 200,
          price: 100,
          image:
            "https://ae01.alicdn.com/kf/Sb05a329922164df4925a0ba586bd940as/1pc-Face-Towel-Absorbent-Pure-Hand-Face-Cleaning-Hair-Shower-Microfiber-Towels-Bathroom-Home-Hotel-for.jpg_350x350xz.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },

        {
          pid: "pid1",
          name: "Waterproof Laptop Backpack Men USB 18 Inch Backpacks Oxford Black Solid Color Large Capacity Rucksacks Teen Student School Bags",
          price_diff: 200,
          price: 210,
          image:
            "https://ae01.alicdn.com/kf/S2d2aab382b7b4e5da894dde6438bc5aea/Waterproof-Laptop-Backpack-Men-USB-18-Inch-Backpacks-Oxford-Black-Solid-Color-Large-Capacity-Rucksacks-Teen.jpg_220x220.jpg_.webp",
          payment_type: "10 Slots",
          stock_supply: 20,
          collateral: 20,
          shipping_tax: false,
          shipping_label: "Free shipping",
          shipping_icon: "pi user",
          discount_color: "var(--text-b)",
          discount_label: "TheRock77",
        },
      ],
    },
  ],
});
