apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
      - ./A/k8s/*
      - ./A/k8s-dev/*         
build:
  local:
    useDockerCLI: true
    push: false
    concurrency: 0
  artifacts:
    - image: pairfy/service-seller
      context: service-seller
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .                         
    - image: pairfy/service-product
      context: service-product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .               
    - image: pairfy/service-gate
      context: service-gate
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .