apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  master: mongodb+srv://doadmin:n1Uc306OG92ba78g@private-master-ab71c199.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=master
  slave: mongodb+srv://doadmin:n1Uc306OG92ba78g@private-master-ab71c199.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=master
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-config
data:
  redis: redis://redis-streaming-srv:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
data:
  micro-store: redis://micro-store:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rater-config
data:
  micro-store: redis://micro-store:6379
