apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  master: mongodb+srv://doadmin:n1Uc306OG92ba78g@private-master-ab71c199.mongo.ondigitalocean.com/admin?authSource=admin&replicaSet=master&tls=true
  slave: mongodb+srv://doadmin:n1Uc306OG92ba78g@private-master-ab71c199.mongo.ondigitalocean.com/admin?authSource=admin&replicaSet=master&tls=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-config
data:
  redis: redis://redis-streaming-srv:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
data:
  micro-store: redis://cache-store:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rater-config
data:
  micro-store: redis://rater-store:6379
