apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      role: micro-notifications
  template:
    metadata:
      labels:
        role: micro-notifications
    spec:
      containers:
        - name: micro-notifications
          image: alphaicterus/micro-notifications 
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_TIMEOUT
              value: "120000"
            - name: MONGO_DB_NAME
              value: "srv-notifications"  
            - name: TELEGRAM_API
              value: 6435046627:AAFb1DkrdQY-hcEWUwUh3Yq1lqDlJJoxulc        
            - name: MONGO_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master                            
            - name: EVENT_BUS_URI
              valueFrom:
                configMapKeyRef:
                  name: streaming-config
                  key: redis                              
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"