export default () => ({
  productData: [
    {
      id: "1000",
      code: "P948324950",
      name: "Bamboo Watch",
      description: "Product Description",
      image: "bamboo-watch.jpg",
      price: 65,
      category: "Accessories",
      quantity: 24,
      inventoryStatus: "stock",
      rating: 5,
    },
    {
      id: "1001",
      code: "P331814905",
      name: "Black Watch",
      description: "Product Description",
      image: "black-watch.jpg",
      price: 72,
      category: "Accessories",
      quantity: 61,
      inventoryStatus: "stock",
      rating: 4,
    },
    {
      id: "1002",
      code: "P918324950",
      name: "Blue Band",
      description: "Product Description",
      image: "blue-band.jpg",
      price: 79,
      category: "Fitness",
      quantity: 2,
      inventoryStatus: "low",
      rating: 3,
    },
    {
      id: "1003",
      code: "P147324950",
      name: "Blue T-Shirt",
      description: "Product Description",
      image: "blue-t-shirt.jpg",
      price: 29,
      category: "Clothing",
      quantity: 25,
      inventoryStatus: "stock",
      rating: 5,
    },
    {
      id: "1004",
      code: "P333324810",
      name: "Bracelet",
      description: "Product Description",
      image: "bracelet.jpg",
      price: 15,
      category: "Accessories",
      quantity: 73,
      inventoryStatus: "stock",
      rating: 4,
    },
    {
      id: "1005",
      code: "P948524920",
      name: "Brown Purse",
      description: "Product Description",
      image: "brown-purse.jpg",
      price: 120,
      category: "Accessories",
      quantity: 0,
      inventoryStatus: "out",
      rating: 4,
    }
  ],
});
