export const schemeCategories = [
  "development_team",
  "tokenomics",
  "community",
  "trading_metrics",
];

export const dependencyTreeCategories = ["trading_metrics"];

export const scoreMatrix = [
  [0.0, 0.0],
  [0.0, 0.0],
  [0.0, 4.0],
  [2.0, 0.0],
  [0.5, 0.0],
  [1.0, 0.0],
  [0.0, 1.0, 0.0],
  [0.0, 1.0, 0.0],
  [0.0, 0.2, 0.5],
  [3.0, 2.0, 0.0],
  [0.0, 0.5, 1.0],
  [1.5, 0.0],
  [1.5, 0.0],
  [2.0, 0.0],
  [0.5, 0.0, 0.5],
  [0.0, 0.5],
  [0.0, 0.5, 1.0],
  [0.0, 2.0, 2.0],
  [0.0, 0.5, 0.0],
  [0.5, 0.0, 0.5],
  [0.0, 0.5, 0.0],
  [0.5, 0.0, 0.5],
  [0.0, 0.5, 1.0, 0.0],
  [1.0, 0.0, 1.0],
  [0.0, 0.5, 0.5],
  [1.0, 0.0],
  [0.5, 0.0],
  [0.0, 0.5],
  [0.5, 0.0],
  [0.0, 2.0, 0.0],
  [0.0, 0.0, 0.5, 1.0],
  [0.0, 0.0, 0.5, 1.0, 1.0],
  [0.0, 1.0, 0.0],
];

export const originalQuestionScheme = [
  {
    id: 0,
    tag: "DT1-0",
    category: "development_team",
    category_index: 0,
    name: "Conflict of Interest Disclosure",
    question: "Are you Affiliated with the project or own any tokens?",
    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 0.0,
  },
  {
    id: 1,
    tag: "DT2-1",
    category: "development_team",
    category_index: 0,
    name: "Read Whitepaper",
    question: "Did you read the whitepaper?",
    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 0.0,
  },
  {
    id: 2,
    tag: "DT3-2",
    category: "development_team",
    category_index: 0,
    name: "Anonymous Team",
    question: "Is the development team anonymous?",
    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 4.0 },
    ],
    max_score: 4.0,
  },
  {
    id: 3,
    tag: "DT4-3",
    category: "development_team",
    category_index: 0,
    name: "Identity Verification",
    question:
      "Can you verify that each member of the Development team is a real person?",
    options: [
      { id: 1, name: "Yes", value: 2.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 2.0,
  },
  {
    id: 4,
    tag: "DT5-4",
    category: "development_team",
    category_index: 0,
    name: "Prior Experience",
    question:
      "Does the Dev team have the proper experience to execute this project? ",
    options: [
      { id: 1, name: "Yes", value: 0.5 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 0.5,
  },
  {
    id: 5,
    tag: "DT6-5",
    category: "development_team",
    category_index: 0,
    name: "Audit",
    question:
      "Has the project successfully completed an audit by a reputable service provider?",
    options: [
      { id: 1, name: "Yes", value: 1.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 1.0,
  },
  {
    id: 6,
    tag: "DT7-6",
    category: "development_team",
    category_index: 0,
    name: "Plagarism",
    question: "Was there any plagiarism in the whitepaper?",
    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 1.0 },
      { id: 3, name: "N/A", value: 0.0 },
    ],
    max_score: 1.0,
  },
  {
    id: 7,
    tag: "DT8-7",
    category: "development_team",
    category_index: 0,
    name: "Spelling Errors",
    question:
      "Are there grammar, spelling, and punctuation errors in the whitepaper or webpage?",
    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 1.0 },
      { id: 3, name: "N/A", value: 0.0 },
    ],
    max_score: 1.0,
  },
  {
    id: 8,
    tag: "DT9-8",
    category: "development_team",
    category_index: 0,
    name: "Whitepaper Length",
    question: "What is the length of the Whitepaper?",
    options: [
      { id: 1, name: "0 to 5 pages", value: 0.0 },
      { id: 2, name: "6 to 15 pages", value: 0.2 },
      { id: 3, name: ">15 Pages", value: 0.5 },
    ],
    max_score: 0.5,
  },
  {
    id: 9,
    tag: "TK1-9",
    category: "tokenomics",
    category_index: 1,
    name: "Insider Allocation",
    question:
      "What portion of the tokens are held by the Development team or early investors?",
    options: [
      { id: 1, name: "0% to 15%", value: 3.0 },
      { id: 2, name: "16% to 25%", value: 2.0 },
      { id: 3, name: ">25%", value: 0.0 },
    ],
    max_score: 3.0,
  },
  {
    id: 10,
    tag: "TK2-10",
    category: "tokenomics",
    category_index: 1,
    name: "Community Allocation",
    question:
      "What portion of tokens will be available to the general public either through sale or rewards ?",
    options: [
      { id: 1, name: "0% to 49%", value: 0.0 },
      { id: 2, name: "50% to 75%", value: 0.5 },
      { id: 3, name: ">75%", value: 1.0 },
    ],
    max_score: 1.0,
  },
  {
    id: 11,
    tag: "TK3-11",
    category: "tokenomics",
    category_index: 1,
    name: "Vesting",
    question:
      "For tokens reserved for development team and early investors, is there a vesting schedule?",
    options: [
      { id: 1, name: "Yes", value: 1.5 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 1.5,
  },
  {
    id: 12,
    tag: "TK4-12",
    category: "tokenomics",
    category_index: 1,
    name: "Locked Policy",
    question:
      "Is the token minting policy locked so that no changes can be made?",
    options: [
      { id: 1, name: "Yes", value: 1.5 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 1.5,
  },
  {
    id: 13,
    tag: "TK5-13",
    category: "tokenomics",
    category_index: 1,
    name: "Clear Use Case",
    question:
      "Do you clearly understand the use case after reading the whitepaper and reviewing website info?",
    options: [
      { id: 1, name: "Yes", value: 2.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 2.0,
  },
  {
    id: 14,
    tag: "TK6-14",
    category: "tokenomics",
    category_index: 1,
    name: "ISO Fee",
    question:
      "If the project utilizes an Initial Stake Offering, what is the percentage they charge?",
    options: [
      { id: 1, name: "0% to 3%", value: 0.5 },
      { id: 2, name: ">3%", value: 0.0 },
      { id: 3, name: "N/A", value: 0.5 },
    ],
    max_score: 0.5,
  },
  {
    id: 15,
    tag: "TK7-15",
    category: "tokenomics",
    category_index: 1,
    name: "Business Model",
    question:
      "Is the project an already existing business model or the first of its kind?",
    options: [
      { id: 1, name: "Existing", value: 0.0 },
      { id: 2, name: "New", value: 0.5 },
    ],
    max_score: 0.5,
  },
  {
    id: 16,
    tag: "CT1-16",
    category: "community",
    category_index: 2,
    name: "Twitter",
    question: "How many followers does the project have on Twitter?",
    options: [
      { id: 1, name: "<1000", value: 0.0 },
      { id: 2, name: "1000 to 5000", value: 0.5 },
      { id: 3, name: ">5K", value: 1.0 },
    ],
    max_score: 1.0,
  },
  {
    id: 17,
    tag: "CT2-17",
    category: "community",
    category_index: 2,
    name: "Twitter Real Followers",
    question:
      "For the twitter account, does it appear to have actual followers or bots/paid followers?",
    options: [
      { id: 1, name: "Bots", value: 0.0 },
      { id: 2, name: "Real", value: 2.0 },
      { id: 3, name: "N/A", value: 2.0 },
    ],
    max_score: 2.0,
  },
  {
    id: 18,
    tag: "CT3-18",
    category: "community",
    category_index: 2,
    name: "Reddit",
    question: "How many subscribers does the project have on Reddit?",
    options: [
      { id: 1, name: "<1000", value: 0.0 },
      { id: 2, name: ">1K", value: 0.5 },
      { id: 3, name: "N/A", value: 0.0 },
    ],
    max_score: 0.5,
  },
  {
    id: 19,
    tag: "CT4-19",
    category: "community",
    category_index: 2,
    name: "Subreddit Activity",
    question:
      "For the subreddit, does it appear to have an active environment?",
    options: [
      { id: 1, name: "Yes", value: 0.5 },
      { id: 2, name: "No", value: 0.0 },
      { id: 3, name: "N/A", value: 0.5 },
    ],
    max_score: 0.5,
  },
  {
    id: 20,
    tag: "CT5-20",
    category: "community",
    category_index: 2,
    name: "Telegram",
    question: "How many subscribers does the project have on Telegram?",
    options: [
      { id: 1, name: "<1000", value: 0.0 },
      { id: 2, name: ">1K", value: 0.5 },
      { id: 3, name: "N/A", value: 0.0 },
    ],
    max_score: 0.5,
  },
  {
    id: 21,
    tag: "CT6-21",
    category: "community",
    category_index: 2,
    name: "Telegram Activity",
    question: "Does their Telegram appear to have an active environment?",

    options: [
      { id: 1, name: "Yes", value: 0.5 },
      { id: 2, name: "No", value: 0.0 },
      { id: 3, name: "N/A", value: 0.5 },
    ],
    max_score: 0.5,
  },
  {
    id: 22,
    tag: "CT7-22",
    category: "community",
    category_index: 2,
    name: "Discord",
    question: "How many members does the project have on discord?",
    options: [
      { id: 1, name: "<1000", value: 0.0 },
      { id: 2, name: "1000 to 10K", value: 0.5 },
      { id: 3, name: "10K+", value: 1.0 },
      { id: 4, name: "N/A", value: 0.0 },
    ],
    max_score: 1.0,
  },
  {
    id: 23,
    tag: "CT8-23",
    category: "community",
    category_index: 2,
    name: "Discord Activity",
    question: "Does their Discord appear to have an active environment?",
    options: [
      { id: 1, name: "Yes", value: 1.0 },
      { id: 2, name: "No", value: 0.0 },
      { id: 3, name: "N/A", value: 1.0 },
    ],

    max_score: 1.0,
  },
  {
    id: 24,
    tag: "CT9-24",
    category: "community",
    category_index: 2,
    name: "Hodlers",
    question: "How many holders does the token have?",
    options: [
      { id: 1, name: "<1K", value: 0.0 },
      { id: 2, name: ">1K", value: 0.5 },
      { id: 3, name: "N/A", value: 0.5 },
    ],
    max_score: 0.5,
  },
  {
    id: 25,
    tag: "CT10-25",
    category: "community",
    category_index: 2,
    name: "Partnerships",
    question:
      "Do they have any official partnerships with other established projects?",
    options: [
      { id: 1, name: "Yes", value: 1.0 },
      { id: 2, name: "No", value: 0.0 },
    ],

    max_score: 1.0,
  },
  {
    id: 26,
    tag: "CT11-26",
    category: "community",
    category_index: 2,
    name: "Ambassadors",
    question: "Do they have an official ambassador program?",

    options: [
      { id: 1, name: "Yes", value: 0.5 },
      { id: 2, name: "No", value: 0.0 },
    ],

    max_score: 0.5,
  },
  {
    id: 27,
    tag: "CT12-27",
    category: "community",
    category_index: 2,
    name: "Banishment",
    question: "Does the project unfairly ban members from social media?",
    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 0.5 },
    ],

    max_score: 0.5,
  },
  {
    id: 28,
    tag: "CT13-28",
    category: "community",
    category_index: 2,
    name: "Responsiveness",
    question: "Does the team respond to questions promptly and satisfactorily?",
    options: [
      { id: 1, name: "Yes", value: 0.5 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 0.5,
  },
  {
    id: 29,
    tag: "MT1-29",
    category: "trading_metrics",
    category_index: 3,
    name: "Fair Launch",
    question:
      "If the project has had its initial offering, (ISO, IDO, ICO, etc) was it a fair launch?",
    options: [
      { id: 0, name: "Doesn't apply", value: 0.0 },
      { id: 1, name: "Yes", value: 2.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 2.0,
  },
  {
    id: 30,
    tag: "MT2-30",
    category: "trading_metrics",
    category_index: 3,
    name: "Market cap",
    question: "What is the current diluted market cap of the project?",
    options: [
      { id: 0, name: "Doesn't apply", value: 0.0 },
      { id: 1, name: "<5 Million", value: 0.0 },
      { id: 2, name: "5 to 10 Million", value: 0.5 },
      { id: 3, name: "10 Million +", value: 1.0 },
    ],
    max_score: 1.0,
  },
  {
    id: 31,
    tag: "MT3-31",
    category: "trading_metrics",
    category_index: 3,
    name: "Volume",
    question: "What is the daily trading volume of the Token ?",
    options: [
      { id: 0, name: "Doesn't apply", value: 0.0 },
      { id: 1, name: "<1 Thousand", value: 0.0 },
      { id: 2, name: "1 Thousand to 50 Thousand", value: 0.5 },
      { id: 3, name: "50 Thousand +", value: 1.0 },
      { id: 4, name: "N/A", value: 1.0 },
    ],
    max_score: 1.0,
  },
  {
    id: 32,
    tag: "MT4-32",
    category: "trading_metrics",
    category_index: 3,
    name: "CEX",
    question: "Is the token listed on large centralized exchanges?",
    options: [
      { id: 0, name: "Doesn't apply", value: 0.0 },
      { id: 1, name: "Yes", value: 1.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    max_score: 1.0,
  },
];
