name: interface-main

on:
  push:
    branches:
      - main
    paths:
      - 'interface-main/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 19
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - run: cd interface-main && docker build -t alphaicterus/interface-main .    
      - run: docker push alphaicterus/interface-main
      - uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.OCEAN_API_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8arka
      - run: kubectl rollout restart deployment interface-main

